- hosts: all
  become: yes
  roles:
    - common_hardened
    - auto_assign_roles

- hosts: webservers
  roles:
    - web_common

- hosts: dbservers
  roles:
    - db_common

- hosts: cicd
  roles:
    - cicd_common

- hosts: homelab
  roles:
    - homelab_common
